[theme]
# "light" or "dark", the starting point
base = "dark"

# your accent: buttons, sliders, links, the send arrow
primaryColor = "#78938a"

# the main page
backgroundColor = "#183e4b"

# the sidebar and chat bubbles
secondaryBackgroundColor = "#00202e"

# all your text
textColor = "##d6eadf"

# outlines on boxes and inputs
borderColor = "#2A3446"

# "sans serif", "serif" or "monospace"
font = "serif"

# a different font just for titles



# "none", "small", "medium", "large", "full"
baseRadius = "full"
[[theme.fontFaces]]
family = "Newsreader"
url = "https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,200..800;1,6..72,200..800&display=swap"
weight = 500
style = "medium"